###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import typing
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder
from baml_py.type_builder import TypeBuilder as _TypeBuilder, ClassPropertyBuilder, ClassPropertyViewer, EnumValueViewer
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(_TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["Inventory",]
        ), enums=set(
          []
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)


    @property
    def Inventory(self) -> "InventoryAst":
        return InventoryAst(self)





class InventoryAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Inventory")
        self._properties: typing.Set[str] = set([ "item",  "quantity",  "price",  "sku", ])
        self._props = InventoryProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "InventoryProperties":
        return self._props


class InventoryViewer(InventoryAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class InventoryProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def item(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("item"))

    @property
    def quantity(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("quantity"))

    @property
    def price(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("price"))

    @property
    def sku(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("sku"))

    




__all__ = ["TypeBuilder"]